##
## Config file for Atom impress package (https://atom.io/packages/impress)
## Parameters in this file are effective in the project that contains this file
## and take precedence over package settings.
## This file is read only when the project is added to Atom.
##

# Path to the main HTML file. (Relative path from the project root.)
mainHtmlPath = 'index.html'

[stepListView]
# stepListViewHeight = 120
